//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostCutterStore
    {
        public int CostCutterID { get; set; }
        public Nullable<double> ProductPrice { get; set; }
        public Nullable<int> ProductID { get; set; }
    }
}
